### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by psikoz** [BlaXpirit/critter#2]
Hello, I designed a logo for your project. If you like it, i will send a pr.

- I wrote '' irc '' in the style of the Gitter logo.
- I used the Gitter color.
- I did emphasize the messaging feature.
- I loyal to the original font.

![critter](https://user-images.githubusercontent.com/40601249/42274627-13272a3c-7f96-11e8-9271-2ffa895607cc.jpg)

**Comment by oprypin** [comment]
Thanks but I'm not interested.
